### ISSUE TITLE
Smartthings won't display DS18B20 temprature

### ISSUE THREAD

**Issue by danshome** [ovidiupruteanu/SmartExpanse#1]
It's possible I don't have things configured properly, but I've tried everything to get the temp from the DS18B20 to report to the Smartthings controller but it always seems to display the temp from the internal sensor.

**Comment by thefederalway** [comment]
I'm having the same issue, just about to return the device to Amazon.

**Comment by ovidiupruteanu** [comment]
Does the sensor device and the main device show the same temperature? Could you post a screenshot from the SmartThings classic app?
